sudo: required
language: python
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_21a71743d5f8_key -iv $encrypted_21a71743d5f8_iv -in deploy.enc -out ./deploy -d
  - sudo service mysql stop
  - wget --no-check-certificate 'https://docs.google.com/uc?export=download&id='$DBGDRIVEID -O db/init.sql
  - docker-compose up -d db redis
  - docker-compose build backend
script:
  - docker-compose run --entrypoint /bin/bash backend -c "pytest app/tests"
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag pragaleriabackend_backend:latest $REGISTRY_USER/pragaleriabackend
  - docker push $REGISTRY_USER/pragaleriabackend
deploy:
  provider: script
  script: ./deploy.sh $SERVER_USER $SERVER_IP deploy
  on:
    branch: master
