version: "3.3"
services:
  backend:
    build: src
    ports:
      - "80:80"
    volumes:
      - './src:/opt'
    environment:
      - config=development
      - MYSQL_ROOT_PASSWORD=Password12#
      - MYSQL_DATABASE=pragaleroe1
  db:
    image: mysql:5.6.40
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Password12#
      - MYSQL_DATABASE=pragaleroe1
