version: "3.3"
services:
  backend:
    build: src
    ports:
      - "8000:8000"
    volumes:
      - './src:/opt'
      - './logs/gunicorn:/logs'
    environment:
      - config=development
      - MYSQL_ROOT_PASSWORD=Password12#
      - MYSQL_DATABASE=pragaleroe1
    restart: unless-stopped
    command: gunicorn -c gunicorn.conf.py run:app
    depends_on:
      - db
  db:
    image: mysql:5.6.40
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Password12#
      - MYSQL_DATABASE=pragaleroe1
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    build: ./nginx
    volumes:
      - "./logs/ngnix:/var/log/nginx"
    ports:
    - "80:80"
    container_name: nginx
    depends_on:
    - backend

  redis:
    image: redis
    volumes:
    - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    - "./logs/redis:/var/log/redis"
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped