version: "3.3"
services:
  backend:
    build: src
    ports:
      - "8000:8000"
    volumes:
      - './src:/opt'
    environment:
      - config=development
      - MYSQL_ROOT_PASSWORD=Password12#
      - MYSQL_DATABASE=pragaleroe1
    restart: unless-stopped
    command: gunicorn -c gunicorn.conf.py run:app
    depends_on:
      - db
  db:
    image: mysql:5.6.40
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Password12#
      - MYSQL_DATABASE=pragaleroe1
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    build: ./nginx
    ports:
    - "80:80"
    container_name: nginx
    depends_on:
    - backend

  redis:
    image: redis
    restart: unless-stopped
