version: "3.3"
services:
  db:
    image: mysql:5.6.40
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Password12#
      - MYSQL_DATABASE=pragaleroe1